version: 2

updates:
  - package-ecosystem: "composer1"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "composer"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "npm"
      - "dependencies"
