name: Deploy Review App

on:
  pull_request:
    types: [ opened, closed, synchronize ]

env:
  APPNAME: sq1
  SERVER: dokku01
  SERVER_URL: ${{ secrets.TEST_DOMAIN }}

jobs:
  deploy_review_app:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize') && github.repository == 'moderntribe/square-one'
    steps:
      - name: Cloning repo for Pull Requests
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Cloning Actions Repos
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: moderntribe/actions
          token: ${{ secrets.GH_BOT_TOKEN }}
          path: .github/actions
          ref: add_basic_sq1

      - name: Set common variables
        uses: ./.github/actions/utils/common-variables
        with:
          base_branch: ${{ github.event.pull_request.head.ref }}

      - name: Create review app ${{ env.REVIEW_APP }}
        uses: ./.github/actions/dokku/create-review-app
        with:
          app_name: ${{ env.APPNAME }}
          review_app_name: ${{ env.REVIEW_APP }}
          server: ${{ env.SERVER }}
          server_url: ${{ env.SERVER_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
          gha_url: ${{ env.GHA_URL }}

      - name: Build Node
        uses: ./.github/actions/square1/build-node

      - name: Commit Files Node Files
        uses: ./.github/actions/utils/commit-files
        with:
          folder: ./wp-content/

      - name: Deploy to ${{ env.REVIEW_APP }}
        uses: ./.github/actions/deploy/gitdeploy
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          server: "dokku@${{ env.SERVER_URL }}"
          app: ${{ env.REVIEW_APP }}
          branch: ${{ env.BRANCH }}

      - name: Slack Message success
        uses: ./.github/actions/utils/slack-message-deploy
        if: success()
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          message: ":green_check: Successful on Review App Deployment"
          app_url: "${{ env.REVIEW_APP }}.${{ env.SERVER_URL }}"
          gha_url: ${{ env.GHA_URL }}
          color: "good"

      - name: Slack Message failure
        uses: ./.github/actions/utils/slack-message-deploy
        if: failure()
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          message: ":x: Failed on Review App Deployment"
          app_url: "${{ env.REVIEW_APP }}.${{ env.SERVER_URL }}"
          gha_url: ${{ env.GHA_URL }}
          color: "bad"

  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.repository == 'moderntribe/square-one'
    steps:

      - name: Cloning Actions Repos
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: moderntribe/actions
          token: ${{ secrets.GH_BOT_TOKEN }}
          path: .github/actions
          ref: add_basic_sq1

      - name: Set common variables
        uses: ./.github/actions/utils/common-variables

      - name: Delete review app ${{ env.REVIEW_APP }}
        uses: ./.github/actions/dokku/delete-review-app
        with:
          app_name: ${{ env.APPNAME }}
          review_app_name: ${{ env.REVIEW_APP }}
          server: ${{ env.SERVER }}
          github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
          gha_url: ${{ env.GHA_URL }}

      - name: Slack Message failure
        uses: ./.github/actions/utils/slack-message-deploy
        if: failure()
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          message: ":x: Failed to Destroy App"
          app_url: "${{ env.REVIEW_APP }}.${{ env.SERVER_URL }}"
          gha_url: ${{ env.GHA_URL }}
          color: "bad"
