name: Deploy Test

on:
  push:
    branches:
      - server/test

env:
  APPNAME: sq1

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    # only run on push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/server/test' && github.repository == 'moderntribe/square-one'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Test
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://${{ secrets.TEST_DEPLOY_USER }}@${{ secrets.TEST_DOMAIN }}:22/${{ env.APPNAME }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SUCCESS
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          text: ":green_check: Server/Test App Deployment Successful "
          attachments: |
            [
              {
                "color": "good",
                "fields": [
                  {
                    "title": "Test App URL",
                    "value": "${{ env.APPNAME }}.${{ secrets.TEST_DOMAIN }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]

      - name: FAILURE
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          text: ":x:  Server/Test Test App Deployment Failed"
          attachments: |
            [
              {
                "color": "bad",
                "fields": [
                  {
                    "title": "Test App URL",
                    "value": "${{ env.APPNAME }}.${{ secrets.TEST_DOMAIN }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]