name: Deploy Review App

on:
  pull_request:
    types: [ opened, closed, synchronize ]

env:
  APPNAME: sq1
  SERVER: ${{ secrets.TEST_DOMAIN }}
  ACTIONS_TAG: add_basic_sq1

jobs:
  deploy_review_app:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize') && github.repository == 'moderntribe/square-one'
    steps:
      - name: Cloning repo for Pull Requests
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Cloning Actions Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: moderntribe/actions
          path: .github/actions
          token: ${{ secrets.GH_BOT_TOKEN }}
          ref: ${{ env.ACTIONS_TAG }}

      - name: Set common variables
        uses: ./.github/actions/utils/common-variables
        with:
          base_branch: ${{ github.event.pull_request.head.ref }}

      # - name: Setup SSH
      #   uses: ./.github/actions/utils/ssh-agent
      #   with:
      #     ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     server: "${{ env.SERVER }}"

      # - name: Create review app ${{ env.REVIEW_APP }}
      #   uses: ./.github/actions/dokku/create-review-app
      #   with:
      #     app_name: ${{ env.APPNAME }}
      #     review_app_name: ${{ env.REVIEW_APP }}
      #     server: ${{ env.SERVER }}
      #     github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
      #     gha_url: ${{ env.GHA_URL }}

      # - name: Build Node
      #   uses: ./.github/actions/square1/build-node

      # - name: Commit Files Node Files
      #   uses: ./.github/actions/utils/commit-files
      #   with:
      #     folder: ./wp-content/

      # - name: Deploy to ${{ env.REVIEW_APP }}
      #   uses: ./.github/actions/deploy/gitdeploy
      #   with:
      #     git_url: "dokku@${{ env.SERVER }}:${{ env.REVIEW_APP }}"
      #     branch: ${{ env.BRANCH }}

      - name: Slack Notification
        if: success()|| failure() || cancelled()
        uses: ./.github/actions/utils/slack-message-deploy
        with:
          branch: ${{ env.BRANCH }}
          environment: ${{ env.REVIEW_APP }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          app_url: "${{ env.REVIEW_APP }}.${{ env.SERVER }}"
          gha_url: ${{ env.GHA_URL }}
          status: ${{ job.status }}

  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.repository == 'moderntribe/square-one'
    steps:

      - name: Cloning Actions Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: moderntribe/actions
          path: .github/actions
          token: ${{ secrets.GH_BOT_TOKEN }}
          ref: ${{ env.ACTIONS_TAG }}

      - name: Set common variables
        uses: ./.github/actions/utils/common-variables

      - name: Delete review app ${{ env.REVIEW_APP }}
        uses: ./.github/actions/dokku/delete-review-app
        with:
          app_name: ${{ env.APPNAME }}
          review_app_name: ${{ env.REVIEW_APP }}
          server: ${{ env.SERVER }}
          github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
          gha_url: ${{ env.GHA_URL }}

      - name: Slack Notification
        if: failure()
        uses: ./.github/actions/utils/slack-message-deploy
        with:
          branch: ${{ env.BRANCH }}
          environment: ${{ env.REVIEW_APP }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          app_url: "${{ env.REVIEW_APP }}.${{ env.SERVER }}"
          gha_url: ${{ env.GHA_URL }}
          status: ${{ job.status }}
