name: Deploy Review App

on:
  pull_request:
    types: [ opened, closed, synchronize ]

env:
  APPNAME: sq1
  SERVER: ${{ secrets.TEST_DOMAIN }}

jobs:
  create_review_app:
    uses: moderntribe/square-one/.github/workflows/reusable-create.yml@add_deploy_folder
    with:
      app_name: ${{ env.APPNAME }}
      review_app_name: ${{ env.REVIEW_APP }}
      server: ${{ env.SERVER }}
      gha_url: ${{ env.GHA_URL }}
    secrets:
      github_pat_token: ${{ secrets.GH_BOT_TOKEN }}

    # runs-on: ubuntu-latest
    # if: (github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize')
    # steps:
    #   - name: Set common variables
    #     uses: moderntribe/actions/utils/common-variables@v1
    #     with:
    #       base_branch: ${{ github.event.pull_request.head.ref }}

    #   - name: Create review app ${{ env.REVIEW_APP }}
    #     uses: moderntribe/actions/dokku/create-review-app@v1
    #     with:
    #       app_name: ${{ env.APPNAME }}
    #       review_app_name: ${{ env.REVIEW_APP }}
    #       server: ${{ env.SERVER }}
    #       github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
    #       gha_url: ${{ env.GHA_URL }}

  deploy_review_app:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize')
    steps:
      - name: Cloning repo for Pull Requests
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set common variables
        uses: moderntribe/actions/utils/common-variables@v1
        with:
          base_branch: ${{ github.event.pull_request.head.ref }}

      - name: Setup SSH
        uses: moderntribe/actions/utils/ssh-agent@v1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          server: "${{ env.SERVER }}"

      - name: Build Node
        uses: moderntribe/actions/square1/build-node@v1

      - name: Commit Files Node Files
        uses: moderntribe/actions/utils/commit-files@v1
        with:
          folder: ./wp-content/

      - name: Deploy to ${{ env.REVIEW_APP }}
        uses: moderntribe/actions/deploy/gitdeploy@v1
        with:
          git_url: "dokku@${{ env.SERVER }}:${{ env.REVIEW_APP }}"
          branch: ${{ env.BRANCH }}

      - name: Slack Notification
        if: success()|| failure() || cancelled()
        uses: moderntribe/actions/utils/slack-message-deploy@v1
        with:
          branch: ${{ env.BRANCH }}
          environment: ${{ env.REVIEW_APP }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          app_url: "${{ env.REVIEW_APP }}.${{ env.SERVER }}"
          gha_url: ${{ env.GHA_URL }}
          status: ${{ job.status }}

  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Set common variables
        uses: moderntribe/actions/utils/common-variables@v1

      - name: Delete review app ${{ env.REVIEW_APP }}
        uses: moderntribe/actions/dokku/delete-review-app@v1
        with:
          app_name: ${{ env.APPNAME }}
          review_app_name: ${{ env.REVIEW_APP }}
          server: ${{ env.SERVER }}
          github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
          gha_url: ${{ env.GHA_URL }}

      - name: Slack Notification
        if: failure()
        uses: moderntribe/actions/utils/slack-message-deploy@v1
        with:
          branch: ${{ env.BRANCH }}
          environment: ${{ env.REVIEW_APP }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          app_url: "${{ env.REVIEW_APP }}.${{ env.SERVER }}"
          gha_url: ${{ env.GHA_URL }}
          status: ${{ job.status }}
