name: Deploy Test

on:
  push:
    branches:
      - server/test

jobs:
  deploy_app:
    uses: moderntribe/square-one/.github/workflows/dokku-deploy.yml@add_deploy_folder
    with:
      app_name: sq1
      branch: ${{ github.ref }}
      is_review_app: false
    secrets:
      github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
      server: ${{ secrets.TEST_DOMAIN }}
      ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}