name: Deploy Review App

on:
  pull_request:
    types: [ opened, closed, synchronize ]

env:
  APPNAME: sq1
  SERVER: ${{ secrets.TEST_DOMAIN }}

jobs:
  create_review_app:
    if: (github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize')
    uses: moderntribe/actions/.github/workflows/create-review-app.yml@review_app_workflow
    with:
      # workflows don't support env
      app_name: sq1
    secrets:
      github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
      server: ${{ secrets.TEST_DOMAIN }}


  deploy_review_app:
    if: (github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize')
    uses: moderntribe/squareone/.github/workflows/deploy-dokku.yml@add_deploy_folder
    with:
      # workflows don't support env
      app_name: sq1
      branch: ${{ github.event.pull_request.head.ref }}
      is_review_app: true
    secrets:
      github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
      server: ${{ secrets.TEST_DOMAIN }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  destroy_review_app:
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: moderntribe/actions/.github/workflows/delete-review-app.yml@review_app_workflow
    with:
      # workflows don't support env
      app_name: sq1
    secrets:
      github_pat_token: ${{ secrets.GH_BOT_TOKEN }}
      server: ${{ secrets.TEST_DOMAIN }}
