name: 'ESLint'
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'wp-content/plugins/core/**.js'
      - 'wp-content/themes/core/**.js'
      - 'wp-content/plugins/core/**.pcss'
      - 'wp-content/themes/core/**.pcss'
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get Node.js version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install and validate
        run: |
          yarn install
          npm run validate

      - name: Lint
      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint_flags: '-c ${{ github.workspace }}/.eslintrc --ignore-path ${{ github.workspace }}/.eslintignore ${{ github.workspace }}/wp-content/{*themes,plugins*}/core/**/*.js'
